name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest test/test_google_maps_api.py -s -v
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          KEY: ${{ secrets.KEY }}


      - name: Copy history from gh-pages to allure-results
        run: |
          sudo mkdir -p allure-results/history
          sudo cp -R $GITHUB_WORKSPACE/.github/workflows/gh-pages/history/* allure-results/history/

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Update Allure history
        run: |
          cp -R allure-report/history/* ./.github/gh-pages/history/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.API_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
