name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Allure Commandline
        run: |
          sudo apt-add-repository ppa:qameta/allure
          sudo apt-get update
          sudo apt-get install allure

      - name: Run tests
        run: |
          python -m pytest test/test_google_maps_api.py -s -v --alluredir=reports
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          KEY: ${{ secrets.KEY }}

      - name: Generate Allure report
        run: allure generate reports/allure-results -o reports/allure-report

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: reports/allure-report
