name: Automation tests

on:
  workflow_dispatch:
    schedule:
      - cron: '0 2 * * *'

jobs:
  api-tests:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Run API-tests via docker-compose
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        KEY: ${{ secrets.KEY }}
      run: |
          docker-compose up --exit-code-from regression || true
    - name: Generate Allure Report
      run: sudo docker-compose run regression /bin/sh -c "allure generate allure-results --clean -o allure-report"

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        token: ${{ secrets.CI_TOKEN }}
        branch: gh-pages
        folder: allure-report
        clean: true


